Ingesting posts

In [15]:
import duckdb

# Path to your massive 5.48 GB file
target_file = "/Users/nash/Documents/ConspiracyComments/r_conspiracy_posts.jsonl"

# Query to grab the single absolute maximum timestamp formatted as a readable date
query = f"""
    SELECT 
        MAX(to_timestamp(CAST(created_utc AS BIGINT))) AS latest_post_date
    FROM read_json_auto('{target_file}')
"""

print("Streaming the file to pinpoint the latest timestamp...")
latest_date_df = duckdb.query(query).df()
print("\nExtraction Complete:")
print(latest_date_df)

Streaming the file to pinpoint the latest timestamp...

Extraction Complete:
           latest_post_date
0 2026-03-28 10:19:30+13:00

Checking columns to see if posts contain metadata

In [23]:
# Check if the scraped metadata already exists in your local data
query = "SELECT url, media, secure_media_embed FROM read_json_auto('/Users/nash/Documents/ConspiracyComments/r_conspiracy_posts.jsonl') WHERE media IS NOT NULL LIMIT 5"
mediadf = duckdb.query(query).df()

In [24]:
mediadf.columns

Index(['url', 'media', 'secure_media_embed'], dtype='object')

In [26]:
for x in mediadf['media']:
    print(x)

{'oembed': {'author_name': 'RT', 'author_url': 'https://www.youtube.com/user/RussiaToday', 'description': "Israel's critics and enemies will see the United States as the side to be blamed for the ongoing violence in the Gaza Strip, believes Congressman Ron Paul. He says the US should review its unconditional support of the Jewish state.", 'height': 338, 'html': '<iframe class="embedly-embed" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F6C756NOPyDA%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D6C756NOPyDA&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F6C756NOPyDA%2Fhqdefault.jpg&key=522baf40bd3911e08d854040d3dc5c07&type=text%2Fhtml&schema=youtube" width="600" height="338" scrolling="no" frameborder="0" allowfullscreen></iframe>', 'provider_name': 'YouTube', 'provider_url': 'https://www.youtube.com/', 'thumbnail_height': 90, 'thumbnail_url': 'https://i.embed.ly/1/image?url=https%3A%2F%2Fi.ytimg.com%2Fvi%2F6C756NOPyDA%2Fhqdefault.jpg&key=522baf40bd3911e08d854040d3dc5c07', 'thumbnail_width': 120, 'title': 'Ron Paul on Israel, Crisis, Obama', 'type': 'video', 'url': 'http://www.youtube.com/watch?v=6C756NOPyDA', 'version': '1.0', 'width': 600}, 'type': 'uk.youtube.com'}
{'oembed': {'author_name': 'Adam Chronister', 'author_url': 'https://www.youtube.com/user/mechanismstudios', 'description': None, 'height': 344, 'html': '<iframe width="459" height="344" src="https://www.youtube.com/embed/TQ4iIM8Eljc?feature=oembed&enablejsapi=1&enablejsapi=1&enablejsapi=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 'provider_name': 'YouTube', 'provider_url': 'https://www.youtube.com/', 'thumbnail_height': 360, 'thumbnail_url': 'https://i.ytimg.com/vi/TQ4iIM8Eljc/hqdefault.jpg', 'thumbnail_width': 480, 'title': 'Cameras in Digital Convert Boxes! BEWARE!!!!', 'type': 'video', 'url': None, 'version': '1.0', 'width': 459}, 'type': 'youtube.com'}
{'oembed': {'author_name': 'Curtis Duncan', 'author_url': 'https://www.youtube.com/user/Thanks719', 'description': None, 'height': 344, 'html': '<iframe width="459" height="344" src="https://www.youtube.com/embed/6hpPkLKucaA?feature=oembed&enablejsapi=1&enablejsapi=1&enablejsapi=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 'provider_name': 'YouTube', 'provider_url': 'https://www.youtube.com/', 'thumbnail_height': 360, 'thumbnail_url': 'https://i.ytimg.com/vi/6hpPkLKucaA/hqdefault.jpg', 'thumbnail_width': 480, 'title': 'Killer Swine Flu Vaccine Soon to Be Released, Part 2', 'type': 'video', 'url': None, 'version': '1.0', 'width': 459}, 'type': 'youtube.com'}
{'oembed': {'author_name': 'bj4077', 'author_url': 'https://www.youtube.com/user/bj4077', 'description': None, 'height': 344, 'html': '<iframe width="459" height="344" src="https://www.youtube.com/embed/Tt7zD9p80gA?feature=oembed&enablejsapi=1&enablejsapi=1&enablejsapi=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 'provider_name': 'YouTube', 'provider_url': 'https://www.youtube.com/', 'thumbnail_height': 360, 'thumbnail_url': 'https://i.ytimg.com/vi/Tt7zD9p80gA/hqdefault.jpg', 'thumbnail_width': 480, 'title': 'Eye In The Sky', 'type': 'video', 'url': None, 'version': '1.0', 'width': 459}, 'type': 'youtube.com'}
{'oembed': {'author_name': None, 'author_url': None, 'description': 'Global Warming Propaganda Exposed', 'height': 271, 'html': '<iframe class="embedly-embed" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.ustream.tv%2Fembed%2Frecorded%2F1391917%3Fhtml5ui&url=http%3A%2F%2Fwww.ustream.tv%2Frecorded%2F1391917&image=http%3A%2F%2Fstatic-cdn2.ustream.tv%2Fi%2Fvideo%2Fpicture%2F0%2F1%2F1%2F1391%2F1391917%2F1_520526_1391917%2C640x360%2Cb%2C1%3A1.jpg&key=522baf40bd3911e08d854040d3dc5c07&type=text%2Fhtml&schema=ustream" width="435" height="271" scrolling="no" frameborder="0" allowfullscreen></iframe>', 'provider_name': 'Ustream.tv', 'provider_url': 'http://ustream.tv', 'thumbnail_height': 360, 'thumbnail_url': 'https://i.embed.ly/1/image?url=http%3A%2F%2Fstatic-cdn2.ustream.tv%2Fi%2Fvideo%2Fpicture%2F0%2F1%2F1%2F1391%2F1391917%2F1_520526_1391917%2C640x360%2Cb%2C1%3A1.jpg&key=522baf40bd3911e08d854040d3dc5c07', 'thumbnail_width': 640, 'title': 'The Great Global Warming Swindle', 'type': 'video', 'url': None, 'version': '1.0', 'width': 435}, 'type': 'ustream.tv'}

In [28]:
for y in mediadf['secure_media_embed']:
    print(y)

{'content': '"<iframe class=\\"embedly-embed\\" src=\\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F6C756NOPyDA%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D6C756NOPyDA&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F6C756NOPyDA%2Fhqdefault.jpg&key=522baf40bd3911e08d854040d3dc5c07&type=text%2Fhtml&schema=youtube\\" width=\\"600\\" height=\\"338\\" scrolling=\\"no\\" frameborder=\\"0\\" allowfullscreen></iframe>"', 'height': '338', 'media_domain_url': '"https://www.redditmedia.com/mediaembed/7pbs0"', 'scrolling': 'false', 'width': '600'}
{'content': '"<iframe width=\\"459\\" height=\\"344\\" src=\\"https://www.youtube.com/embed/TQ4iIM8Eljc?feature=oembed&enablejsapi=1&enablejsapi=1&enablejsapi=1\\" frameborder=\\"0\\" allow=\\"autoplay; encrypted-media\\" allowfullscreen></iframe>"', 'height': '344', 'media_domain_url': '"https://www.redditmedia.com/mediaembed/7ya99"', 'scrolling': 'false', 'width': '459'}
{'content': '"<iframe width=\\"459\\" height=\\"344\\" src=\\"https://www.youtube.com/embed/6hpPkLKucaA?feature=oembed&enablejsapi=1&enablejsapi=1&enablejsapi=1\\" frameborder=\\"0\\" allow=\\"autoplay; encrypted-media\\" allowfullscreen></iframe>"', 'height': '344', 'media_domain_url': '"https://www.redditmedia.com/mediaembed/90dai"', 'scrolling': 'false', 'width': '459'}
{'content': '"<iframe width=\\"459\\" height=\\"344\\" src=\\"https://www.youtube.com/embed/Tt7zD9p80gA?feature=oembed&enablejsapi=1&enablejsapi=1&enablejsapi=1\\" frameborder=\\"0\\" allow=\\"autoplay; encrypted-media\\" allowfullscreen></iframe>"', 'height': '344', 'media_domain_url': '"https://www.redditmedia.com/mediaembed/9ips8"', 'scrolling': 'false', 'width': '459'}
{'content': '"<iframe class=\\"embedly-embed\\" src=\\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.ustream.tv%2Fembed%2Frecorded%2F1391917%3Fhtml5ui&url=http%3A%2F%2Fwww.ustream.tv%2Frecorded%2F1391917&image=http%3A%2F%2Fstatic-cdn2.ustream.tv%2Fi%2Fvideo%2Fpicture%2F0%2F1%2F1%2F1391%2F1391917%2F1_520526_1391917%2C640x360%2Cb%2C1%3A1.jpg&key=522baf40bd3911e08d854040d3dc5c07&type=text%2Fhtml&schema=ustream\\" width=\\"435\\" height=\\"271\\" scrolling=\\"no\\" frameborder=\\"0\\" allowfullscreen></iframe>"', 'height': '271', 'media_domain_url': '"https://www.redditmedia.com/mediaembed/9uv2x"', 'scrolling': 'false', 'width': '435'}

Getting media titles from posts

In [34]:

import json
import pandas as pd

file_path = '/Users/nash/Documents/ConspiracyComments/r_conspiracy_posts.jsonl'

extracted_records = []
target_limit = 10000

print("Streaming 5.48GB file natively in Python to bypass SQL schema crashes...")

# Open the file and process it line-by-line (highly memory efficient)
with open(file_path, 'r', encoding='utf-8') as f:
    for line in f:
        try:
            # Parse the raw string into a Python dictionary
            data = json.loads(line)
            
            # Safely navigate the messy dictionary structure
            media = data.get('media')
            
            # Only proceed if 'media' is actually a dictionary (ignoring False, None, etc.)
            if isinstance(media, dict):
                oembed = media.get('oembed', {})
                
                # Double-check that oembed is also a dictionary
                if isinstance(oembed, dict):
                    title = oembed.get('title')
                    
                    # If we successfully found a title, save the record
                    if title:
                        extracted_records.append({
                            'id': data.get('id', ''),
                            'author': data.get('author', ''),
                            'score': data.get('score', 0),
                            'url': data.get('url', ''),
                            'link_title': title,
                            # Use .get() with a default empty string for missing descriptions
                            'link_description': oembed.get('description') or '' 
                        })
                        
                        # Stop scanning once we hit your limit
                        if len(extracted_records) >= target_limit:
                            break
                            
        except json.JSONDecodeError:
            # If a line is corrupted, just silently skip it
            continue

# Convert our clean list of dictionaries directly into a Pandas DataFrame
links_df = pd.DataFrame(extracted_records)

# Combine the payload for your sentence-transformers model
links_df['combined_payload'] = links_df['link_title'] + " - " + links_df['link_description']

print(f"Extraction successful. Retained {len(links_df)} rich media-link records.")
links_df.head()

Streaming 5.48GB file natively in Python to bypass SQL schema crashes...
Extraction successful. Retained 10000 rich media-link records.

,id,author,score,url,link_title,link_description,combined_payload
0,7pbs0,rhoadesb2,17,http://uk.youtube.com/watch?v=6C756NOPyDA,"Ron Paul on Israel, Crisis, Obama",Israel's critics and enemies will see the Unit...,"Ron Paul on Israel, Crisis, Obama - Israel's c..."
1,7ya99,xandercruise,35,http://www.youtube.com/watch?v=TQ4iIM8Eljc,Cameras in Digital Convert Boxes! BEWARE!!!!,,Cameras in Digital Convert Boxes! BEWARE!!!! -
2,90dai,CurtisDuncan,3,http://www.youtube.com/watch?v=6hpPkLKucaA,"Killer Swine Flu Vaccine Soon to Be Released, ...",,"Killer Swine Flu Vaccine Soon to Be Released, ..."
3,9ips8,plutocrat24,1,http://www.youtube.com/watch?v=Tt7zD9p80gA,Eye In The Sky,,Eye In The Sky -
4,9uv2x,antifacist,0,http://www.ustream.tv/recorded/1391917,The Great Global Warming Swindle,Global Warming Propaganda Exposed,The Great Global Warming Swindle - Global Warm...

Exploratory analysis of comments

In [6]:
import pandas as pd

# Define your file path
file_path = '/Users/nash/Documents/ConspiracyComments/r_conspiracy_comments3.jsonl'

# Load just the first 10,000 rows to explore
df = pd.read_json(file_path, nrows=10000, lines = True)

# Display the first 5 rows to see what the columns look like
df.head()

,all_awardings,associated_award,author,author_created_utc,author_flair_background_color,author_flair_css_class,author_flair_richtext,author_flair_template_id,author_flair_text,author_flair_text_color,...,subreddit,subreddit_id,subreddit_name_prefixed,subreddit_type,top_awarded_type,total_awards_received,treatment_tags,name,ups,author_cakeday
0,[],NaN,LurkingFromBelow,NaN,None,None,[],NaN,None,None,...,conspiracy,t5_2qh4r,r/conspiracy,public,NaN,0,[],t1_gfz82vv,3,NaN
1,[],NaN,redditready1986,1.337874e+09,None,None,[],NaN,None,None,...,conspiracy,t5_2qh4r,r/conspiracy,public,NaN,0,[],t1_gfz82x0,0,NaN
2,[],NaN,bgny,1.291781e+09,None,None,[],NaN,None,None,...,conspiracy,t5_2qh4r,r/conspiracy,public,NaN,0,[],t1_gfz830e,7,NaN
3,[],NaN,walkclothed,1.348939e+09,None,None,[],NaN,None,None,...,conspiracy,t5_2qh4r,r/conspiracy,public,NaN,0,[],t1_gfz83rj,2,NaN
4,[],NaN,Myskinisnotmyown,1.370322e+09,None,None,[],NaN,None,None,...,conspiracy,t5_2qh4r,r/conspiracy,public,NaN,0,[],t1_gfz83sl,2,NaN

In [2]:
df.columns

Index(['all_awardings', 'associated_award', 'author', 'author_created_utc',
       'author_flair_background_color', 'author_flair_css_class',
       'author_flair_richtext', 'author_flair_template_id',
       'author_flair_text', 'author_flair_text_color', 'author_flair_type',
       'author_fullname', 'author_patreon_flair', 'author_premium', 'awarders',
       'body', 'can_gild', 'can_mod_post', 'collapsed',
       'collapsed_because_crowd_control', 'collapsed_reason', 'comment_type',
       'controversiality', 'created_utc', 'distinguished', 'edited', 'gilded',
       'gildings', 'id', 'is_submitter', 'link_id', 'locked', 'no_follow',
       'parent_id', 'permalink', 'quarantined', 'removal_reason',
       'retrieved_on', 'score', 'send_replies', 'stickied', 'subreddit',
       'subreddit_id', 'subreddit_name_prefixed', 'subreddit_type',
       'top_awarded_type', 'total_awards_received', 'treatment_tags', 'name',
       'ups', 'author_cakeday'],
      dtype='object')

In [4]:
for comment in df['body'][:10]:
    print(comment)

I think owls eat mice entirely and then spit up balls of hair and fur later. Im not certain, i havnt seen much animal related stuff recently.


Fun story though, fits the sub.
It's the least I could do. I am all about helping folks that have disabilities.
It wasn't good that no one listened to him, because he was right.  Guess you've been brainwashed away from the truth by communists, because you don't do your own research in to the subject.
Fill that Condom up with silicone lube and insert a bullet vibrator so it sits right under the head and thank me in the morning

/probator
No one said it was, friend.
i dont think anyone will disagree
You're playing with fire emboldening dark forces. Who follows you to recover the funds using blackmail?
> Patriots overrode the crown, then the south.

You know, the south considered themselves "patriots" too, and that they were fighting for some version of "TRUTH" and against "TYRANNY". They convinced themselves that a presidential election was illegitimate, and that the guy coming in was the worst thing that could ever happen to them, and that he was totally going to impose the will of northern elites onto southern "true Americans". Then they even convinced themselves that they could legally secede from the union. And the lame duck president did fuck all to calm and unify the nation, and arguably made things worse.

And now, much later, many of those same states seem ready to take a similar stance that they did long ago, for similarly bad reasons, to defend similarly bad men, and you're lining up with them. And the part that really sticks in my craw, the thing that really just flabbergasts me, is that you claim that you're doing the right thing. But you're not. When you're on the side that's arguing for 10s of millions of votes to be thrown out, you're not on the side of the "good guys", and history will judge you poorly for it.
Lots of seagulls here mid pacific
you forgot "as long as we can continue to squeeze you like a grape, just fucking shut up and eat your spam"

Incorporating comments in duckdb

In [7]:
import duckdb
import pandas as pd

# 1. Define your files. You can type them out as a list, 
# or if they are all in a folder, just use a wildcard like 'downloads/*.jsonl'
file_paths = ['/Users/nash/Documents/ConspiracyComments/*.jsonl']

# 2. Write the DuckDB Query with a deduplication step
query = f"""
    -- Step A: Combine all files and drop the overlapping duplicates based on the unique comment 'id'
    WITH deduplicated_comments AS (
        SELECT DISTINCT id, parent_id
        FROM read_json_auto({file_paths})
    )
    
    -- Step B: Run our reply-counting math on the clean, deduplicated list
    SELECT 
        parent_id, 
        COUNT(*) as reply_count
    FROM deduplicated_comments
    WHERE parent_id LIKE 't1_%'
    GROUP BY parent_id
    ORDER BY reply_count DESC
    LIMIT 500
"""

# 3. Execute
print("Scanning multiple files, filtering out overlaps, and crunching the numbers...")
battlegrounds_df = duckdb.query(query).df()

print("Scan complete. Here are your top 5 battlegrounds:")
battlegrounds_df.head()

Scanning multiple files, filtering out overlaps, and crunching the numbers...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scan complete. Here are your top 5 battlegrounds:

    parent_id  reply_count
0  t1_g0ylmj4         1723
1  t1_dka1xu5          797
2  t1_g0iaeb4          293
3  t1_n6f2gh1          222
4  t1_g7eej7n          212

In [6]:
battlegrounds_df

      parent_id  reply_count
0    t1_g0ylmj4         1723
1    t1_dka1xu5          797
2    t1_g0iaeb4          293
3    t1_n6f2gh1          222
4    t1_g7eej7n          212
..          ...          ...
495  t1_k5ptlai           49
496  t1_j8hi7qs           49
497  t1_gki03fy           49
498  t1_diy76g5           49
499  t1_m3e62tw           49

[500 rows x 2 columns]

In [8]:
import duckdb
import pandas as pd
import re

# 1. Your files and your target ID
file_paths = ['/Users/nash/Documents/ConspiracyComments/*.jsonl'] # Update this to your list
target_id = 'g0iaeb4' # Replace with your top ID (without the 't1_' prefix)


# Clean the target_id in Python just to be safe (removes t1_ or t3_ if you accidentally pasted it)
clean_target = target_id.replace('t1_', '').replace('t3_', '')

# The Bulletproof Query using wildcards (%)
query = f"""
    SELECT id, parent_id, author, score, body
    FROM read_json_auto({file_paths})
    WHERE id LIKE '%{clean_target}' 
       OR parent_id LIKE '%{clean_target}'
"""

print(f"Extracting thread for {clean_target} using wildcards...")
thread_df = duckdb.query(query).df()

# Split them up again (using string containment to be safe)
parent_comment = thread_df[thread_df['id'].str.contains(clean_target, na=False)]
replies = thread_df[thread_df['parent_id'].str.contains(clean_target, na=False)]

print(f"Extraction complete. Found the parent comment and {len(replies)} direct replies.")
# 2. The Extraction Query
# We are asking DuckDB to grab the parent comment itself (id = target) 
# AND every comment that directly replied to it (parent_id = t1_target)
query = f"""
    SELECT id, parent_id, author, score, body
    FROM read_json_auto({file_paths})
    WHERE id = '{target_id}' OR parent_id = 't1_{target_id}'
"""

print(f"Extracting the conversation thread for {target_id}...")
thread_df = duckdb.query(query).df()

# 3. Split the DataFrame into 'The Claim' and 'The Debate'
parent_comment = thread_df[thread_df['id'] == target_id]
replies = thread_df[thread_df['parent_id'] == f't1_{target_id}']

print(f"Extraction complete. Found the parent comment and {len(replies)} direct replies.")

Extracting thread for g0iaeb4 using wildcards...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Extraction complete. Found the parent comment and 293 direct replies.
Extracting the conversation thread for g0iaeb4...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Extraction complete. Found the parent comment and 293 direct replies.

In [9]:
# 1. Create a new column containing the length of the string
# We use fillna('') just in case there are any empty rows so it doesn't throw an error
replies['body_length'] = replies['body'].fillna('').str.len()

# 2. Sort the replies from longest to shortest
longest_replies = replies.sort_values(by='body_length', ascending=False)

# 3. Print the top 5 longest essays
print("THE 5 LONGEST REPLIES IN THE THREAD")
print("=========================================")

for index, row in longest_replies.head(5).iterrows():
    print(f"\nAuthor: {row['author']} | Character Count: {row['body_length']}")
    print("-" * 40)
    print(row['body'])
    print("\n" + "*"*40)

THE 5 LONGEST REPLIES IN THE THREAD
=========================================

Author: Donald_John-Trump | Character Count: 4801
----------------------------------------
[1](https://np.reddit.com/r/conspiracy/comments/i30m7u/trump_said_this_in_2012_now_hes_president/)

[2](https://np.reddit.com/r/conspiracy/comments/ht3blh/trump_warns_epsteins_island_a_cesspool_in_2015/)

[3](https://np.reddit.com/r/conspiracy/comments/hxxfsp/black_trump_supporter_shot_dead_after_interview/)

[4](https://np.reddit.com/r/conspiracy/comments/fqxjt9/picture_on_rpics_comparing_xi_to_the_coronavirus/)

[5](https://np.reddit.com/r/conspiracy/comments/i1r1g1/bill_clinton_named_on_pedo_island_in_actually/)

[6](https://np.reddit.com/r/conspiracy/comments/g3cnfo/70k_upvotes_on_a_post_claiming_trump_supporter/)

[7](https://np.reddit.com/r/conspiracy/comments/fgqu21/based_plant_lady_knows_joe_bidens_campaign_is_a/)

Or how about the numerous comments from pro Trump accounts that got approved despite breaking rules?

[1](https://np.reddit.com/r/conspiracy/comments/i05ifl/look_at_how_the_fakenews_and_reddit_shills_are/fzne21v/)

[2](https://np.reddit.com/r/conspiracy/comments/hisjvk/the_only_candidate_in_american_history_who_cannot/fwi40mh/)

[3, this one directed at a moderator](https://np.reddit.com/r/conspiracy/comments/gsyovr/shills_are_massdownvoting_almost_everything_that/fs9eo7v/)

[4](https://np.reddit.com/r/conspiracy/comments/gnlcim/ivy_league_fucks_who_unanimously_opposed/frajpx5/)

[5, this one *from* a moderator](https://np.reddit.com/r/conspiracy/comments/hy64w5/supporters_of_trump_have_coopted_this_sub_it_used/fzbmtwm/)

[6](https://np.reddit.com/r/conspiracy/comments/hfkqbu/meta_rconspiracy_does_not_have_a_right_wing_bias/fvyamyr/)

[7](https://np.reddit.com/r/conspiracy/comments/gqwb56/the_fbi_documents_that_put_barack_obama_in_the/frveh8i/)

Or threads from pro Trump users getting approved with invalid submission statements

[1](https://np.reddit.com/r/conspiracy/comments/g4tcbd/trump_gives_zero_fucks/fnziwha/)

[2](https://np.reddit.com/r/conspiracy/comments/i473qc/video_catches_joe_biden_rubbing_little_girls_hand/g0glfe0/)

[3](https://np.reddit.com/r/conspiracy/comments/i1ubkg/heres_another_pic_of_clinton_on_epsteins_jet_for/g00g2wy/)

[4](https://np.reddit.com/r/conspiracy/comments/i164x8/trump_mentioned_in_released_maxwell_documents/fzvrd8a/)

[5](https://np.reddit.com/r/conspiracy/comments/hx23bs/dni_declassifies_trump_flynn_defensive_briefing/fz3fh6o/)

[6](https://np.reddit.com/r/conspiracy/comments/hqkk5y/lead_attorney_in_child_protection_services/fxylhhk/)

[7](https://np.reddit.com/r/conspiracy/comments/hl9ot3/rconspiracy_the_last_few_days/fwy245c/)

[8](https://np.reddit.com/r/conspiracy/comments/gekgi8/biden_media_and_feminists_resurrect_clintonera/fpo2aez/)

[9](https://np.reddit.com/r/conspiracy/comments/ge5ewh/papaya_tests_positive_for_covid19/fplr6qo/)

[10](https://np.reddit.com/r/conspiracy/comments/g91w85/dear_senator_biden_you_are_a_traitor_jfk_jr/for31fs/)

[11](https://np.reddit.com/r/conspiracy/comments/g6mw7b/cnbc_just_confirmed_what_we_already_knew_we_were/foaqjd8/)

[12](https://np.reddit.com/r/conspiracy/comments/g4tcbd/trump_gives_zero_fucks/fnziwha/)

[13](https://np.reddit.com/r/conspiracy/comments/i0z7o4/found_in_unsealed_maxwell_documents_serious/fztnqkw/)

[14](https://np.reddit.com/r/conspiracy/comments/hzmpan/ghislaine_maxwell_documents_from_2015_unsealing/fzk6f3k/)

[15](https://np.reddit.com/r/conspiracy/comments/hzl09y/a_tale_of_two_drugs/fzjtuoo/)

[16](https://np.reddit.com/r/conspiracy/comments/hx4m7u/hong_kong_vs_portland_protestors_quite_ironic/fz40xhr/)

[17](https://np.reddit.com/r/conspiracy/comments/hs0xhj/at_some_point_it_will_not_be_safe_for_them_to/fy7n400/)

[18](https://np.reddit.com/r/conspiracy/comments/ho4e37/kanye_on_democrats/fxg9wp0/)

[19](https://np.reddit.com/r/conspiracy/comments/hnjdd3/aoc_removes_her_mask_in_order_to_blow_covid/fxc9id2/)

[20](https://np.reddit.com/r/conspiracy/comments/hn2ik3/people_are_waking_up/fx8zsru/)

[21](https://np.reddit.com/r/conspiracy/comments/hmey2z/trump_dropping_truth_bombs_on_nascar_hoax/fx50rb6/)

[22](https://np.reddit.com/r/conspiracy/comments/hl4vr9/so_now_twitter_says_you_cant_say_he_when_refering/fwwvi3a/)

[23](https://np.reddit.com/r/conspiracy/comments/hh6wpl/barr_russiagate_scandal_is_closest_we_have_come/fw8cjvp/)

[24](https://np.reddit.com/r/conspiracy/comments/hgtw14/antifa_leader_found_guilty_of_being_a_pedophile/fw695xt/)

[25](https://np.reddit.com/r/conspiracy/comments/hg8v6n/video_antifa_set_fire_to_a_black_owned_hair_salon/fw2g3l6/)

[26](https://np.reddit.com/r/conspiracy/comments/hg8h2i/bottled_water_made_by_whole_foods_and_sold_on/fw2fw6k/)

[27](https://np.reddit.com/r/conspiracy/comments/hg81xf/joe_biden_ancestor_owned_slaves_according_to/fw2f2wy/)

edit: Notice how the mod completely ignored the dozens of instances of pro Trump users being allowed to break the rules.

****************************************

Author: Distasteful_Username | Character Count: 3787
----------------------------------------
The person who posted all those links is cool and all, but it's largely anecdotal. They didn't go through every single post- so sure, it supports their argument, but I don't think it's 1000% sufficient.

Luckily, however, there's a tool that lets you see the demographics of a subreddit in terms of what other communities its users frequent. By looking at both what is posted on this subreddit as well as the data on the communities that members of this subreddit frequent, we can paint a more accurate picture of the political leanings of this subreddit.

First, check out the data at this link: https://subredditstats.com/subreddit-user-overlaps/conspiracy

The highest subreddit that's left leaning on this list other than /r/topmindsofreddit (which probably brigades this sub, inflating their rating) is /r/latestagecapitalism at rank 44. Some of the most popular alt-right/right-leaning subreddits are in the top 5-20 ish spots, with over 80+ alt-right/right-leaning subreddits in the top 150 spots.

Not only by ranking is this sub far-right, left-leaning subreddits have numerical overlap scores which are small fractions of that of subreddits such as /r/donaldtrump, /r/tucker_carlson, and /r/conservative (>6-7 vs. ~2). Via the algorithm used to compute these scores, we can easily say that a commenter of /r/conspiracy is many more times likely to post in right-leaning subreddits than left-leaning subreddits. If we wanted to get a more accurate picture of user overlap, we could also take into account the sheer volume of right-leaning subreddits in the stats.

People also like to rebut these claims by saying there's also a lot of people from the left-leaning sub /r/politics, but it's overlap rating is #138, being beat out by random subreddits such as /r/dallas and /r/kanye. In the top 150, there's only a handful of left leaning subreddits (~4) with user overlap.

So sure you could make the anecdotal claim that lots of people here support Trump and there's plenty of anecdotal evidence for that, but when these anecdotes are also backed by data as shown above, these claims are difficult to dispute.

I hope you can see that the statement that this subreddit (at the very least) leans to the right is well-supported.

P.S. Also if someone disagrees with this, I'd love it if they were to engage me. I see a lot of people claiming stuff contrary to this, but whenever I post statistics and a reasoned argument nobody has responded :/ ... It's really depressing lol...

Edit: Also, it’s really disappointing that a *moderator* would make the argument that upvotes have any correlation to user opinions. People upvote shit randomly, and what gets upvoted is highly dependent on numerous factors (e.g. time zone, crossposts, picture vs text, ease of content digestion, etc.). Further, upvote counts are HEAVILY fuzzed, especially when you get into the thousands of engagements. With enough organic upvotes, basically anything will go on the front page regardless of downvotes. It’s just really dumb and sad that a moderator of a >1mil subreddit has absolutely zero idea how voting works.

Edit 2: This tool is interesting as well, although it’s potentially more subjective. Feel free to check it out: https://www.shorttails.io/interactive-map-of-reddit-and-subreddit-similarity-calculator/

Edit 3: My bad, misunderstood /r/qult_headquarters. They seem to reference this subreddit a lot, which inflates their ranking. Removed that edit. Thanks to those that pointed that out! I’ll be responding to more comments in a second, I’ve been a bit busy I have a packed schedule haha.

lastly, it’s cliché, but thank you for the awards everybody! i tried to send a message to every person who gave this an award. if i didn’t reach you, that’s my bad! have a good day y’all! 💞

****************************************

Author: Alles_Spice | Character Count: 2578
----------------------------------------
I mean no disrespect to the mods but I think you're not arguing in good faith or charitably interpreting OP's comments. Frankly, if you look at OPs post-history you will see they *are* responding to people in this thread and elsewhere.

I am looking through the top posts of r/conspiracy in the past *week* and these are all the pro-Trump "circlejerk" posts I can find. Please note I am defining "pro-Trump" not just based on the content of the post but the *poster* and their post history, with regards to the general message of the post "anti-enemies of Trump from a historically pro-Trump account should be considered a "pro-Trump" post:

* https://breakingwide.com/calls-for-joe-biden-to-debate-trump-intensifies-jill-hell-be-there/

* https://www.reddit.com/r/conspiracy/comments/i4i7d9/besties_john_podesta_and_stephen_colbert/

* https://www.reddit.com/r/conspiracy/comments/i4r775/hydroxychloroquine_was_approved_for_medical_use/

* Even this meta-post is from a pro-Trump account: https://www.reddit.com/r/conspiracy/comments/i4kxqe/you_know_youve_reached_peak_gaslighting_when_the/

* https://www.reddit.com/r/conspiracy/comments/i3wwlu/not_all_biden_supporters_are_pedos/

* https://www.reddit.com/r/conspiracy/comments/i4rmxq/churches_and_gyms_are_too_risky_but_reopening_gay/

* https://www.marketwatch.com/story/new-york-city-to-set-up-covid-checkpoints-at-bridges-and-tunnels-2020-08-05

* https://blog.nomorefakenews.com/2020/08/05/cdc-director-redfield-letter-should-have-destroyed-his-career/

* https://www.reddit.com/r/conspiracy/comments/i4wt39/they_cant_use_the_emergency_authorization_to_push/

Now I don't have the time to look at every single post but within 8 hours I was able to look through the post histories of many OPs on r/conspiracy. Many of whom are pushing pro-Trump agendas and comments in many other subs, but keeping it more subtle in r/conspiracy - because they likely know they will get shut down if they are blatently pro-Trump.

**I think it is undeniable that this sub has been infected with Qanon people and their like but I disagree with OP here when they claim that this sub is a Pro-Trump "circlejerk" there are clearly plenty of people on this sub that are suspicious of this billionaire playboy who has historically exploited people for his own gain.**


There is clearly an "info-war" battle going on here in r/conspiracy. Too many people making it a "Biden vs Trump" situation when in reality, the rational members of r/conspiracy recognize that something is up with BOTH Biden and Trump many people in their social circles.

****************************************

Author: judgecucken72 | Character Count: 2150
----------------------------------------
[This](https://www.reddit.com/r/conspiracy/comments/i0ldzy/you_tell_em/) was a pretty great one after all the criticism this sub had for Greta and David Hogg for being children used as political puppets.

Anytime the MSM or scientific experts disagree with Trump, this subreddit sees a steady stream of posts attempting to vindicate Trump's position. Right now we see it with a bunch of posts overestimating hydrochloroquine as a treatment for covid-19:

https://www.reddit.com/r/conspiracy/comments/fpko9m/rcoronavirus_blocks_letter_to_president_from_ny/
https://www.reddit.com/r/conspiracy/comments/i1z55u/they_cant_remove_child_porn_from_the_internet_but/
https://www.reddit.com/r/conspiracy/comments/fxomfu/medical_doctor_talks_about_his_success_with/
https://www.reddit.com/r/conspiracy/comments/fv0r87/6227_doctors_in_30_countries_find/

Always propping up the few studies that fit this narrative and assuming the more comprehensive, double blind studies that show HCQ isn't very effective are the real propaganda.

(we also saw this with Trump's claims of election rigging and being spied on, obamagate/spygate was pushed on this sub for a while before folks seemed to realize not enough people outside of the most Trump fans were buying it.)

[This post](https://www.reddit.com/r/conspiracy/comments/i0z5t0/from_unsealed_maxwell_documents_witness_interview/) gained more upvotes than any other thread in response to the Ghislaine Maxwell files being released. Literally the only new information we learned about Clinton and Epstein is that "two young girls" were there when he was on the island. Virginia and other victims spoken to have outright said they never saw Clinton nor Trump involved, yet only the quotes pertaining to Trump get shared as his vindication.

Ya'll are allowed to be a right-wing echo chamber the same way r/politics and a ton of reddit is a left-wing echo chamber. It would be nice, though, if conservatives and reactionaries on the internet would just admit what they are instead of all the complaining that it's unfair to them when others point out they're just as politically biased as the leftists they criticize.

****************************************

Author: OracularLettuce | Character Count: 1835
----------------------------------------
So for starters, if you "*see posts like yours quite often*", shouldn't that lend credence to the idea that this sub has indeed morphed into a pro-Trump circle jerk? If users regularly point out how much non-conspiracy, pro-Trump content is posted in this sub, maybe there really is a problem? Maybe there actually is a problem with ineffective delineation between conspiracy content, and conspiracy-adjacent political content (I've got some conspiracy theories of my own about why that might be).

Even if it's not true by some metrics—this is a big subreddit after all, the raw quantity of posts is high—perhaps it's worth accepting that the perception is of an overtly pro-Trump narrative.

But either way, this is r/conspiracy. Why would you want proof of *anything*? "*always fail to provide any evidence*" should be the sub's motto, and could honestly supersede most of the sub's rules.

[Yesterday I saw a post](https://np.reddit.com/r/conspiracy/comments/i3qqam/interesting_its_almost_as_if_they_all_got/) claiming that Chester Bennington, Anthony Bourdain, and Chris Cornell were working on an documentary exposé about Hollywood pedophiles before their various suicides. No evidence was provided. Like any of them mentioning it, job ads for the staff required to work on it, name of production company, evidence of funding, evidence of a title or even working title, copyrights, legal representation, anything *anything* *ANYTHING* approaching "proof".

Nope, just a fucking screenshot from Facebook and a bunch of random speculation. No need to question anything there, makes perfect sense. But someone complaining about the rampant astroturfing in this subreddit? Gotta get some proof for that. But ya know, in a way that's easier to read. What am I supposed to do? Click on all those links? Read? Fuck that, I ain't no lib.

****************************************

/var/folders/ym/6mr3ypl97rj6468b4m65lq240000gp/T/ipykernel_58834/3519156370.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  replies['body_length'] = replies['body'].fillna('').str.len()

In [23]:
longest_replies

,id,parent_id,author,score,body,body_length
11,g0ih5ig,t1_g0iaeb4,Donald_John-Trump,2474.0,[1](https://np.reddit.com/r/conspiracy/comment...,4801
75,g0j7a7f,t1_g0iaeb4,Distasteful_Username,880.0,The person who posted all those links is cool ...,3787
282,g0m8dzt,t1_g0iaeb4,Alles_Spice,2.0,I mean no disrespect to the mods but I think y...,2578
83,g0j956r,t1_g0iaeb4,judgecucken72,57.0,[This](https://www.reddit.com/r/conspiracy/com...,2150
86,g0jay9q,t1_g0iaeb4,OracularLettuce,77.0,"So for starters, if you ""*see posts like yours...",1835
...,...,...,...,...,...,...
128,g0jxzzj,t1_g0iaeb4,Gigatron_0,4.0,Trash,5
178,g0kmqu5,t1_g0iaeb4,yaboimissesezlayups,3.0,Rekt,4
107,g0jkp9k,t1_g0iaeb4,TOADSTOOL__SURPRISE,1.0,Lol,3
31,g0isnfd,t1_g0iaeb4,Cocoadicks,2.0,Lol,3
233,g0lb42x,t1_g0iaeb4,CanUPlsUninstall,3.0,🤡,1

In [10]:
battlegrounds_df.columns

Index(['parent_id', 'reply_count'], dtype='object')

In [11]:
import duckdb

# Point this to your folder of JSONL files
file_paths = ['/Users/nash/Documents/ConspiracyComments/*.jsonl']

query = f"""
    SELECT 
        MIN(to_timestamp(CAST(created_utc AS BIGINT))) AS earliest_comment,
        MAX(to_timestamp(CAST(created_utc AS BIGINT))) AS most_recent_comment
    FROM read_json_auto({file_paths})
"""

print("Scanning files for the timeline boundaries...")
date_range_df = duckdb.query(query).df()
date_range_df

Scanning files for the timeline boundaries...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

           earliest_comment       most_recent_comment
0 2008-01-30 03:02:37+13:00 2026-03-31 11:11:16+13:00

setting up zero shot embeddings for search of comments to identify disussions around epistemic credibility

In [12]:
import numpy as np
from sentence_transformers import SentenceTransformer, util

# 1. Load a lightweight, highly accurate embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

# 2. Define your precise semantic anchors (keep them lean and conceptual)
anchors = [
    "There is overwhelming empirical evidence to support this.",
    "This is the established consensus among field experts.",
    "The data definitively proves this assertion.",
    "There is zero verifiable evidence for that claim.",
    "That assertion is clearly false and unsupported.",
    "You cannot reasonably believe that based on current data."
]

# 3. Pre-compute anchor embeddings (do this once and cache them)
anchor_embeddings = model.encode(anchors, convert_to_tensor=True)

def analyze_text(input_text, threshold=0.45):
    """
    Checks if the input text semantically aligns with any of your core concepts.
    """
    # Embed the incoming target text
    target_embedding = model.encode(input_text, convert_to_tensor=True)
    
    # Compute cosine similarities between target and all anchors
    similarities = util.cos_sim(target_embedding, anchor_embeddings)[0]
    
    # Find the best matching anchor
    max_score_idx = np.argmax(similarities.cpu().numpy())
    max_score = similarities[max_score_idx].item()
    best_match = anchors[max_score_idx]
    
    # Print diagnostic evaluation
    print(f"Input: '{input_text}'")
    print(f"Best Anchor Match: '{best_match}'")
    print(f"Semantic Match Score: {max_score:.4f}")
    
    if max_score >= threshold:
        print("Verdict: Strong conceptual alignment detected.\n")
        return True
    else:
        print("Verdict: Below threshold. Ignored.\n")
        return False

# --- Quick Test Loop ---
print("--- Running Concept Vector Verification ---\n")
analyze_text("The peer-reviewed literature shows a clear correlation.")
analyze_text("I reckon it's true because my uncle told me so on the weekend.")

README.md: 0.00B [00:00, ?B/s]

--- Running Concept Vector Verification ---

Input: 'The peer-reviewed literature shows a clear correlation.'
Best Anchor Match: 'There is overwhelming empirical evidence to support this.'
Semantic Match Score: 0.4043
Verdict: Below threshold. Ignored.

Input: 'I reckon it's true because my uncle told me so on the weekend.'
Best Anchor Match: 'That assertion is clearly false and unsupported.'
Semantic Match Score: 0.3026
Verdict: Below threshold. Ignored.

False

Anchors based on different epistemic stances

In [13]:
anchors_absolutist = ["This is an undisputed fact.", "The data proves this absolutely."]
anchors_evaluativist = ["The balance of evidence supports this interpretation.", "We must weigh the counterarguments."]
anchors_hedges = ["It could be argued that...", "Perhaps there is a correlation."]

Loading factappeal dataset 

https://arxiv.org/abs/2510.10658

Retrieved from https://github.com/guymorlan/factappeal.git

In [35]:
import pandas as pd

# Point Pandas to the new folder in your home directory
local_train_path = '/Users/nash/factappeal/train.csv'

print("Loading local FACTAPPEAL dataset...")
fact_df = pd.read_csv(local_train_path)

print(f"Loaded {len(fact_df)} annotated sentences.")
fact_df.head()

Loading local FACTAPPEAL dataset...
Loaded 2256 annotated sentences.

,sentence,annotation
0,Using campaign funds for personal use is a vio...,<Fact_No_Appeal>Using campaign funds for perso...
1,The move by North Korea was the first of its k...,<Fact_No_Appeal>The move by North Korea was th...
2,It seems like her job had an insurance policy ...,<Fact_No_Appeal>It seems like her job had an i...
3,He knew that his own parents had been investig...,<Fact_No_Appeal>He knew that his own parents h...
4,What was also interesting is that the shy ones...,<Fact_No_Appeal>What was also interesting is t...

In [36]:
import duckdb

con = duckdb.connect()
output_file = '/Users/nash/Documents/ConspiracyComments/lexical_scores_full.parquet'

# Extract all URLs and their domains, with upvotes
print(con.execute(f"""
    WITH urls AS (
        SELECT 
            id,
            upvotes,
            controversiality,
            -- Extract the full URL
            UNNEST(regexp_extract_all(text, 'https?://[^\s\)\]"]+')) AS url
        FROM '{output_file}'
        WHERE text LIKE '%http%'
    ),
    domains AS (
        SELECT
            id,
            upvotes,
            controversiality,
            url,
            -- Extract just the domain
            regexp_extract(url, 'https?://(?:www\.)?([^/\s]+)') AS domain
        FROM urls
    )
    SELECT 
        domain,
        COUNT(*) as citations,
        ROUND(AVG(upvotes), 2) as avg_upvotes,
        ROUND(MEDIAN(upvotes), 2) as median_upvotes,
        ROUND(AVG(controversiality), 3) as avg_controversy,
        COUNT(DISTINCT id) as unique_comments
    FROM domains
    WHERE domain != ''
      AND length(domain) > 3
    GROUP BY domain
    ORDER BY citations DESC
    LIMIT 50
""").df().to_string())

<>:48: SyntaxWarning: invalid escape sequence '\s'
<>:51: SyntaxWarning: invalid escape sequence '\.'
<>:48: SyntaxWarning: invalid escape sequence '\s'
<>:51: SyntaxWarning: invalid escape sequence '\.'
/var/folders/ym/6mr3ypl97rj6468b4m65lq240000gp/T/ipykernel_58834/4216252512.py:48: SyntaxWarning: invalid escape sequence '\s'
/var/folders/ym/6mr3ypl97rj6468b4m65lq240000gp/T/ipykernel_58834/4216252512.py:51: SyntaxWarning: invalid escape sequence '\.'

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

                             domain  citations  avg_upvotes  median_upvotes  avg_controversy  unique_comments
0            https://www.reddit.com    2475946         1.32             1.0            0.005          1298010
1           https://www.youtube.com     245849         5.54             2.0            0.065           158502
2          https://en.wikipedia.org     153453         5.92             2.0            0.062           101099
3                  https://youtu.be     149249         5.51             2.0            0.068           108728
4             https://np.reddit.com     115107         4.09             1.0            0.024            48568
5               https://twitter.com      58882         8.87             2.0            0.131            41644
6                https://archive.is      58856         5.27             1.0            0.050            49655
7               https://i.imgur.com      48922         6.44             1.0            0.077            27549
8        https://en.m.wikipedia.org      41263         6.22             2.0            0.061            31899
9            https://old.reddit.com      39099         3.16             1.0            0.055            30036
10           https://www.google.com      38441         5.04             2.0            0.064            32329
11            http://www.reddit.com      37312         3.49             1.0            0.042            26588
12          http://en.wikipedia.org      32504         4.84             2.0            0.028            24249
13           http://www.youtube.com      32101         3.92             2.0            0.025            22198
14                https://imgur.com      29732         7.32             2.0            0.088            20459
15         https://www.reveddit.com      28781         1.25             1.0            0.013             6114
16     https://www.ncbi.nlm.nih.gov      26674         5.29             2.0            0.069            18251
17          https://www.nytimes.com      25837         7.03             2.0            0.092            20321
18      https://www.theguardian.com      23131         7.55             2.0            0.074            19065
19          https://web.archive.org      22268         8.23             2.0            0.046            11891
20          https://www.reuters.com      20932         7.54             2.0            0.069            13401
21              https://www.cdc.gov      19615         4.00             1.0            0.087            15771
22   https://www.washingtonpost.com      19576         7.56             2.0            0.094            16288
23            https://m.youtube.com      18966         5.50             2.0            0.059            16270
24              https://archive.org      18195         5.71             2.0            0.053            11801
25             http://np.reddit.com      15008         2.62             1.0            0.028             5863
26               http://i.imgur.com      14926         8.63             2.0            0.064            10669
27  https://pubmed.ncbi.nlm.nih.gov      13085         4.68             2.0            0.070             8204
28                 http://imgur.com      11817         9.46             2.0            0.088             7365
29               https://nypost.com      11777         6.85             2.0            0.113             9597
30      https://www.dailymail.co.uk      11244         7.35             2.0            0.089             9112
31                https://snewd.com      11005         1.37             1.0            0.025            10980
32              https://www.cnn.com      10993         6.56             2.0            0.090             8797
33              https://www.npr.org      10899         6.58             2.0            0.101             9608
34           https://www.forbes.com      10610         5.51             2.0            0.080             8983
35                    https://x.com      10507         7.63             1.0            0.113             7592
36              https://www.bbc.com      10169         7.03             2.0            0.077             8180
37      http://www.ncbi.nlm.nih.gov       9527         8.82             3.0            0.047             2252
38          https://www.nbcnews.com       9479         6.67             2.0            0.103             7961
39               https://reddit.com       9281         3.37             1.0            0.028             6167
40  https://www.businessinsider.com       9091         6.11             2.0            0.086             7364
41          https://www.cbsnews.com       9012         7.73             3.0            0.069             6819
42       https://mobile.twitter.com       8847         6.90             2.0            0.094             6843
43           https://www.amazon.com       8309         4.23             2.0            0.038             6593
44             https://www.cnbc.com       8154         6.01             2.0            0.073             6818
45               https://archive.ph       8003         9.51             3.0            0.093             3445
46                http://archive.is       7929        12.95             3.0            0.101             4885
47               https://github.com       7911         2.56             1.0            0.021             6842
48                https://i.redd.it       7815         6.44             1.0            0.110             5960
49            https://wikileaks.org       7812        14.58             3.0            0.085             5076

In [37]:
import duckdb
con = duckdb.connect()

# Just look at all the columns available in one file
result = con.execute("""
    SELECT * 
    FROM read_json_auto('/Users/nash/Documents/ConspiracyComments/r_conspiracy_comments3.jsonl',
                        ignore_errors=true)
    LIMIT 1
""").df()

print(result.columns.tolist())

['all_awardings', 'associated_award', 'author', 'author_created_utc', 'author_flair_background_color', 'author_flair_css_class', 'author_flair_richtext', 'author_flair_template_id', 'author_flair_text', 'author_flair_text_color', 'author_flair_type', 'author_fullname', 'author_patreon_flair', 'author_premium', 'awarders', 'body', 'can_gild', 'can_mod_post', 'collapsed', 'collapsed_because_crowd_control', 'collapsed_reason', 'comment_type', 'controversiality', 'created_utc', 'distinguished', 'edited', 'gilded', 'gildings', 'id', 'is_submitter', 'link_id', 'locked', 'no_follow', 'parent_id', 'permalink', 'quarantined', 'removal_reason', 'retrieved_on', 'score', 'send_replies', 'stickied', 'subreddit', 'subreddit_id', 'subreddit_name_prefixed', 'subreddit_type', 'top_awarded_type', 'total_awards_received', 'treatment_tags', 'name', 'ups', 'author_cakeday']

In [38]:
import duckdb
import time

con = duckdb.connect()
PARQUET_PATH = '/Users/nash/Documents/ConspiracyComments/lexical_scores_full.parquet'

print("Initializing tractable deep-path extractions...")
start_time = time.time()

# 1. WIKIPEDIA HISTORICAL CANON
print("Scanning Wikipedia paths...")
con.execute(f"""
    COPY (
        WITH raw_urls AS (
            SELECT unnest(regexp_extract_all(text, 'https?://en\\\\.wikipedia\\\\.org/wiki/[^\\\\s\\\\)\\\\\\\\]\\"]+')) AS url
            FROM '{PARQUET_PATH}'
            WHERE text LIKE '%wikipedia.org/wiki/%'
        ),
        cleaned_paths AS (
            SELECT regexp_extract(url, '/wiki/([^\\\\s\\\\)\\\\]\\"]+)', 1) AS wiki_slug
            FROM raw_urls
        )
        SELECT wiki_slug, COUNT(*) as reference_count
        FROM cleaned_paths
        WHERE wiki_slug != ''
        GROUP BY wiki_slug
        ORDER BY reference_count DESC
        LIMIT 100
    ) TO '/Users/nash/Documents/ConspiracyComments/top_wikipedia_canon.csv' (FORMAT CSV, HEADER);
""")

# 2. YOUTUBE CANON
print("Scanning YouTube Video IDs...")
con.execute(f"""
    COPY (
        WITH raw_urls AS (
            SELECT unnest(regexp_extract_all(text, 'https?://(?:www\\\\.)?(?:youtube\\\\.com|youtu\\\\.be)/[^\\\\s\\\\)\\\\\\\\]\\"]+')) AS url
            FROM '{PARQUET_PATH}'
            WHERE text LIKE '%youtu%'
        ),
        video_ids AS (
            SELECT regexp_extract(url, '(?:v=|\\\\/v\\\\/|embed\\\\/|youtu\\\\.be\\\\/)([^?&\\\\s\\\\)\\\\]\\"]+)', 1) AS video_id
            FROM raw_urls
        )
        SELECT video_id, COUNT(*) as reference_count
        FROM video_ids
        WHERE length(video_id) = 11
        GROUP BY video_id
        ORDER BY reference_count DESC
        LIMIT 100
    ) TO '/Users/nash/Documents/ConspiracyComments/top_youtube_videos.csv' (FORMAT CSV, HEADER);
""")

# 3. PUBMED WEAPONIZED SCIENCE
print("Scanning PubMed identifiers...")
con.execute(f"""
    COPY (
        WITH raw_urls AS (
            SELECT unnest(regexp_extract_all(text, 'https?://(?:www\\\\.)?ncbi\\\\.nlm\\\\.nih\\\\.gov/pubmed/[0-9]+')) AS url
            FROM '{PARQUET_PATH}'
            WHERE text LIKE '%ncbi.nlm.nih.gov/pubmed%'
        ),
        pubmed_ids AS (
            SELECT regexp_extract(url, '/pubmed/([0-9]+)', 1) AS pm_id
            FROM raw_urls
        )
        SELECT pm_id, COUNT(*) as reference_count
        FROM pubmed_ids
        GROUP BY pm_id
        ORDER BY reference_count DESC
        LIMIT 100
    ) TO '/Users/nash/Documents/ConspiracyComments/top_pubmed_studies.csv' (FORMAT CSV, HEADER);
""")

elapsed = time.time() - start_time
print(f"Extraction complete in {elapsed:.1f} seconds! Files saved to your project directory.")

Initializing tractable deep-path extractions...
Scanning Wikipedia paths...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanning YouTube Video IDs...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Scanning PubMed identifiers...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Extraction complete in 10.5 seconds! Files saved to your project directory.

In [40]:
import duckdb
con = duckdb.connect()
PARQUET_PATH = '/Users/nash/Documents/ConspiracyComments/lexical_scores_full.parquet'

# Wikipedia slugs
print(con.execute(f"""
    SELECT 
        regexp_extract(url, '/wiki/([^\\s\\)\\]"]+)') AS wiki_slug,
        COUNT(*) as n
    FROM (
        SELECT UNNEST(regexp_extract_all(text, 'wikipedia.org/wiki/[^\\s\\)\\]"]+')) AS url
        FROM '{PARQUET_PATH}'
        WHERE text LIKE '%wikipedia.org/wiki/%'
    )
    WHERE wiki_slug != ''
    GROUP BY wiki_slug
    ORDER BY n DESC
    LIMIT 30
""").df().to_string())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

                                                     wiki_slug     n
0                                     /wiki/Stockholm_syndrome  1733
1                                  /wiki/Operation_Mockingbird   691
2                                   /wiki/Operation_Northwoods   533
3                                      /wiki/Haavara_Agreement   405
4                                            /wiki/Consumerism   360
5                                /wiki/New_York_Stock_Exchange   347
6                                         /wiki/Reality_tunnel   334
7                                             /wiki/COINTELPRO   313
8                                    /wiki/Operation_Paperclip   299
9             /wiki/Donald_Trump_sexual_misconduct_allegations   296
10  /wiki/Unethical_human_experimentation_in_the_United_States   289
11                            /wiki/Foundations_of_Geopolitics   285
12                  /wiki/Project_for_the_New_American_Century   284
13                             /wiki/2019_Military_World_Games   278
14                                             /wiki/Et_cetera   276
15                                      /wiki/Operation_Popeye   275
16                                       /wiki/Project_MKUltra   269
17                          /wiki/List_of_suicide_crisis_lines   245
18                                        /wiki/Mahatma_Gandhi   244
19                          /wiki/Anne,_Queen_of_Great_Britain   212
20                           /wiki/Queen_of_the_United_Kingdom   212
21                               /wiki/Operation_Earnest_Voice   201
22                                  /wiki/USS_Liberty_incident   198
23  /wiki/A_Clean_Break:_A_New_Strategy_for_Securing_the_Realm   191
24         /wiki/Criticism_of_the_Food_and_Drug_Administration   185
25                                         /wiki/Cloud_seeding   183
26                                          /wiki/Lavon_Affair   179
27                                   /wiki/Georgia_Guidestones   179
28                                 /wiki/Monarchy_of_Australia   174
29                                    /wiki/Monarchy_of_Canada   174

In [39]:
result2 = con.execute("""
    SELECT * 
    FROM read_json_auto('/Users/nash/Documents/ConspiracyComments/r_conspiracy_posts.jsonl',
                        ignore_errors=true)
    LIMIT 1
""").df()

print(result2.columns.tolist())

['archived', 'author', 'author_flair_background_color', 'author_flair_css_class', 'author_flair_richtext', 'author_flair_text', 'author_flair_text_color', 'author_flair_type', 'brand_safe', 'can_gild', 'contest_mode', 'created_utc', 'distinguished', 'domain', 'edited', 'gilded', 'hidden', 'hide_score', 'id', 'is_crosspostable', 'is_reddit_media_domain', 'is_self', 'is_video', 'link_flair_css_class', 'link_flair_richtext', 'link_flair_text', 'link_flair_text_color', 'link_flair_type', 'locked', 'media', 'media_embed', 'no_follow', 'num_comments', 'num_crossposts', 'over_18', 'parent_whitelist_status', 'permalink', 'retrieved_on', 'rte_mode', 'score', 'secure_media', 'secure_media_embed', 'selftext', 'send_replies', 'spoiler', 'stickied', 'subreddit', 'subreddit_id', 'subreddit_name_prefixed', 'subreddit_type', 'suggested_sort', 'thumbnail', 'thumbnail_height', 'thumbnail_width', 'title', 'url', 'whitelist_status', 'name', 'ups', 'upvote_ratio', 'author_cakeday', 'post_hint', 'preview', 'link_flair_background_color', 'is_original_content']

In [41]:
import duckdb
con = duckdb.connect()
PARQUET_PATH = '/Users/nash/Documents/ConspiracyComments/lexical_scores_full.parquet'

print(con.execute(f"""
    SELECT 
        regexp_extract(url, '(?:v=|/v/|embed/|youtu\\.be/)([^?&\\s\\)\\]"]+)', 1) AS video_id,
        COUNT(*) as n
    FROM (
        SELECT UNNEST(regexp_extract_all(text, 'https?://(?:www\\.)?(?:youtube\\.com|youtu\\.be)/[^\\s\\)\\]"]+')) AS url
        FROM '{PARQUET_PATH}'
        WHERE text LIKE '%youtu%'
    )
    WHERE length(video_id) = 11
    GROUP BY video_id
    ORDER BY n DESC
    LIMIT 30
""").df().to_string())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

       video_id     n
0   rdrKCilEhC0  1282
1   O1GCeuSr3Mk   520
2   7Eeo-82Eac8   469
3   bXmuWecIQos   356
4   KpuKu3F0BvY   349
5   6_s1Zbs20aA   347
6   U1Qt6a-vaNM   311
7   Yqb59n69Z80   282
8   uW3a1bw5XlE   274
9   dQw4w9WgXcQ   271
10  09maaUaRT4M   269
11  yuC_4mGTs98   267
12  8DOnAn_PX6M   251
13  9RC1Mepk_Sw   250
14  t_fOYW-GXdc   248
15  gbUK4cFCTPg   237
16  Ddz2mw2vaEg   232
17  KYL94OjXHYY   225
18  5EarOB411BA   224
19  rf78rEAJvhY   221
20  -bYAQ-ZZtEU   219
21  e6Yif7LGFCc   208
22  eJ3RzGoQC4s   207
23  G45WthPTo24   203
24  55tdrnP4rxc   202
25  JOktR-FbzvU   201
26  KVeDKuHPDK8   198
27  ZtlhThIk3iI   197
28  yCzdliixnmI   196
29  -GZFHLAcG8A   191

In [42]:
print(con.execute(f"""
    SELECT 
        regexp_extract(url, '/pubmed/([0-9]+)', 1) AS pubmed_id,
        COUNT(*) as n
    FROM (
        SELECT UNNEST(regexp_extract_all(text, 'https?://(?:www\\.)?ncbi\\.nlm\\.nih\\.gov/pubmed/[0-9]+')) AS url
        FROM '{PARQUET_PATH}'
        WHERE text LIKE '%pubmed%'
    )
    WHERE pubmed_id != ''
    GROUP BY pubmed_id
    ORDER BY n DESC
    LIMIT 30
""").df().to_string())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   pubmed_id    n
0   12145534  195
1   21623535  187
2   17454560  164
3   21058170  151
4   21993250  141
5   11339848  130
6   17114826  122
7   12933322  107
8   22099159  105
9   12849883  102
10  22591873   99
11  21299355   98
12  19106436   96
13  25377033   96
14  19043938   95
15  23902317   95
16  15780490   94
17  24675092   94
18  16870260   93
19  17674242   91
20  12142947   91
21  21907498   89
22  24995277   84
23  18445737   67
24  25198681   51
25  18454680   49
26  23932735   46
27  24791031   45
28  17952650   44
29  19216002   41

In [43]:
import requests
import time

pubmed_ids = ['12145534', '21623535', '17454560', '21058170', '21993250', 
              '11339848', '17114826', '12933322', '22099159', '12849883',
              '22591873', '21299355', '19106436', '25377033', '19043938']

print("Fetching PubMed titles...")
for pmid in pubmed_ids:
    url = f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id={pmid}&retmode=json"
    r = requests.get(url)
    data = r.json()
    try:
        title = data['result'][pmid]['title']
        source = data['result'][pmid]['source']
        print(f"{pmid}: {title} [{source}]")
    except:
        print(f"{pmid}: lookup failed")
    time.sleep(0.4)  # be polite to NCBI

Fetching PubMed titles...
12145534: Abnormal measles-mumps-rubella antibodies and CNS autoimmunity in children with autism. [J Biomed Sci]
21623535: A positive association found between autism prevalence and childhood vaccination uptake across the U.S. population. [J Toxicol Environ Health A]
17454560: A case series of children with apparent mercury toxic encephalopathies manifesting with clinical symptoms of regressive autistic disorders. [J Toxicol Environ Health A]
21058170: Hepatitis B vaccination of male neonates and autism diagnosis, NHIS 1997-2002. [J Toxicol Environ Health A]
21993250: Hypothesis: conjugate vaccines may predispose children to autism spectrum disorders. [Med Hypotheses]
11339848: Autism: a novel form of mercury poisoning. [Med Hypotheses]
17114826: Aluminum adjuvant linked to Gulf War illness induces motor neuron death in mice. [Neuromolecular Med]
12933322: Reduced levels of mercury in first baby haircuts of autistic children. [Int J Toxicol]
22099159: Do aluminum vaccine adjuvants contribute to the rising prevalence of autism? [J Inorg Biochem]
12849883: Elevated levels of measles antibodies in children with autism. [Pediatr Neurol]
22591873: Polio programme: let us declare victory and move on. [Indian J Med Ethics]
21299355: Theoretical aspects of autism: causes--a review. [J Immunotoxicol]
19106436: A comprehensive review of mercury provoked autism. [Indian J Med Res]
25377033: Commentary--Controversies surrounding mercury in vaccines: autism denial as impediment to universal immunisation. [Indian J Med Ethics]
19043938: A possible central mechanism in autism spectrum disorders, part 1. [Altern Ther Health Med]

In [44]:
import duckdb

con = duckdb.connect()

print("Scanning submission metadata...")
query = """
SELECT 
    domain,
    COUNT(*) as total_submissions,
    ROUND(AVG(score), 2) as avg_score,
    MAX(score) as top_score
FROM read_json_auto('/Users/nash/Documents/ConspiracyComments/r_conspiracy_posts*.jsonl', union_by_name=true, ignore_errors=true)
WHERE domain IS NOT NULL 
  AND domain != 'self.conspiracy'
  AND domain != ''
GROUP BY domain
ORDER BY total_submissions DESC
LIMIT 30
"""

print(con.execute(query).df().to_string())

Scanning submission metadata...
                 domain  total_submissions  avg_score  top_score
0             i.redd.it             197111     206.08      76121
1           youtube.com             148570      27.58      64503
2              youtu.be              88698      23.21      30419
3            reddit.com              33893      64.72      33132
4           twitter.com              23960     111.39      31560
5           i.imgur.com              19167     268.15      36780
6             imgur.com              16803     113.09      26225
7         zerohedge.com              10105      56.58      10758
8         m.youtube.com               8787      27.74       7457
9                rt.com               8031      41.02       6714
10      dailymail.co.uk               7690      86.79      17006
11      theguardian.com               7536      48.62       7986
12     activistpost.com               5637      39.45       6879
13          nytimes.com               5632      34.67      10834
14   washingtonpost.com               4939      38.93       8393
15     en.wikipedia.org               4823      65.18      10160
16           rumble.com               4600      35.79       2494
17         infowars.com               4416      22.82       4345
18        np.reddit.com               3961      67.36      18011
19          reuters.com               3926      34.98       4097
20    independent.co.uk               3543      59.38       5374
21          foxnews.com               3493      55.42       5766
22    globalresearch.ca               3352      38.69       5097
23              cnn.com               3316      15.63       2243
24    beforeitsnews.com               3292      12.83       2766
25           archive.is               3220      63.12       7882
26  businessinsider.com               3021      60.44       6565
27      rajacreator.com               2994       1.00          1
28           nypost.com               2929      85.81       9212
29           google.com               2927      39.74      32373

In [45]:
import duckdb

con = duckdb.connect()

print("Extracting top specific URLs and their submission titles...")
query = """
SELECT 
    url,
    -- We take the most commonly used title for this specific URL
    MODE(title) as most_common_title,
    COUNT(*) as submission_count,
    ROUND(AVG(score), 2) as avg_score
FROM read_json_auto('/Users/nash/Documents/ConspiracyComments/r_conspiracy_posts*.jsonl', union_by_name=true, ignore_errors=true)
WHERE url IS NOT NULL 
  AND domain NOT IN ('i.redd.it', 'v.redd.it', 'i.imgur.com', 'imgur.com', 'reddit.com', 'np.reddit.com') -- Filter out pure image/internal links
  AND domain != 'self.conspiracy'
GROUP BY url
HAVING submission_count > 10 -- Only show URLs that have been submitted multiple times
ORDER BY submission_count DESC
LIMIT 30
"""

print(con.execute(query).df().to_string(max_colwidth=80))

Extracting top specific URLs and their submission titles...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

                                                                                url                                                                most_common_title  submission_count  avg_score
0                                                                                                                                                  [deleted by user]             29429      12.98
1   https://www.google.com/amp/s/abc7news.com/amp/sources-jeffrey-epstein-dies-b...                  Sources: Jeffrey Epstein dies by suicide in Manhattan jail cell               121     268.54
2              https://youtube.com/playlist?list=PLmUOtaC-dPk0gGZqxlKzkXCG3Y7m9rUNL                                                                  Occult classics                79       1.25
3                                   http://theinversionofchristianity.blogspot.com/                                                  My views on the New World Order                77       0.82
4                                                      https://youtu.be/36wY5ujpi34                                                        Self similar across scale                50       0.92
5                                                              http://real-ufos.com                                 A website to show to those who think UFOs are BS                49      16.69
6                                       https://www.youtube.com/watch?v=xRml1VROXGg  UFO attacks in Russia. November 12, 2019 at night over Russia flew a strange...                48       0.42
7                                                      https://youtu.be/uaA6kMDPamM  That it's an alien or a strange creature in the forest.. A tourist met a mys...                45       0.04
8                                                      https://youtu.be/QJQ2_oRYoUY  In 2020, there were many aliens in the woods and abandoned areas. people are...                43       0.14
9                                   https://theinversionofchristianity.blogspot.com  Why is there evil in our world if a perfect God created it? Because evil is ...                40       1.45
10                                                            http://real-ufos.com/  Several Astronauts, NASA, CIA, FBI, Army, Air Force officials and rocket sci...                40      28.48
11                             https://www.reveddit.com/y/clarityofsignal/?all=true  Reminder: Use Reveddit To See What The Corrupt Powers That Be, Even Here At ...                37       7.16
12  https://steemit.com/informationwar/@clarityofsignal/where-your-mind-goes-you...  Where Your Mind Goes, Your Energy Flows - 50 Posts Exposing The Censorship, ...                35      23.80
13                                                     https://youtu.be/R1g_ACjECI4  Strange creature similar to an alien was caught in the frame of a video in V...                34       0.00
14  https://saidit.net/s/ConspiracyTrace/comments/a4i0/miscellaneous_theories_co...  Miscellaneous Theories, Conspiracies and Corruption Super Compilation. (120 ...                34       0.53
15                                      https://www.youtube.com/watch?v=nsBGniPF3ZQ  Over 95% of the resources intended to "save" Greece ended up in the hands of...                32      24.34
16                                      https://www.youtube.com/watch?v=AjKOPaC9vPk  Fear Porn: Twitter's Ebola Psychological Warfare [r/EbolaHoax] (watch the br...                32       0.03
17  https://steemit.com/news/@clarityofsignal/massive-truth-drop-large-compilati...  Massive Truth Drop: Large Compilation of Mainstream Media Articles and Inter...                31      41.94
18                                      https://www.youtube.com/watch?v=fMktHEv9rRo  UFO filmed on CCTV in St. Petersburg, a strange unidentified object flew at ...                31       0.55
19                                        https://allin14fun.com/loch-ness-monster/        Scottish whisky worker captures 'clearest ever photo of Loch Ness Monster                31       0.84
20                                     https://www.bitchute.com/video/XCnEcLOnLiPx/  Order From Chaos: I Pet Goat II, Super Bowl 53, False Flags And Illuminati E...                30       4.00
21                                      https://www.youtube.com/watch?v=NLCHKy4he0M  You will see in this video something no one has noticed or mentioned in the ...                30       0.13
22                                                            https://ufopanel.com/  Several Astronauts, NASA, CIA, FBI, Army, Air Force officials, rocket scient...                30      10.53
23  https://wikileaks.org/syria-files/docs/486170_re-.html?fbclid=IwAR0WC7rBliLQ...         Wikileaks Exposes Blatant Corruption from Lloyd Austin, Biden's DoD Pick                29       2.34
24                          https://theintercept.com/2014/02/24/jtrig-manipulation/  How covert agents infiltrate the Internet and destroy reputations. (The Inte...                29      23.97
25  https://chiniquy.wordpress.com/2015/07/01/the-all-mighty-creator-does-not-ha...  This is the Reason Why America, and some European Countries Believe that the...                29       1.38
26  http://theholographicmatrix.blogspot.com/2014/05/i-believe-live-in-holograph...                                                  My views on the New World Order                29       0.90
27  https://www.cia.gov/library/abbottabad-compound/FC/FC2F5371043C48FDD95AEDE7B...  Why Does The CIA’s Government Website Have a Book About The Illuminati Famil...                28      17.64
28                                                     https://youtu.be/osVVn5KfGNE  Mysterious creature is a Ghost hit the frame of the video. the owner was sho...                26       0.19
29                                                     https://youtu.be/O-MH612s3BA  The Message From the Creator to All People of the World: It is Proposed to A...                26       0.08

In [46]:
query = """
SELECT 
    title,
    domain,
    score,
    num_comments,
    upvote_ratio,
    created_utc
FROM read_json_auto('/Users/nash/Documents/ConspiracyComments/r_conspiracy_posts*.jsonl', 
                    union_by_name=true, ignore_errors=true)
WHERE score > 1000
  AND title IS NOT NULL
  AND domain NOT IN ('i.redd.it', 'v.redd.it', 'i.imgur.com', 'imgur.com')
ORDER BY score DESC
LIMIT 50
"""
print(con.execute(query).df()[['title','domain','score','num_comments','upvote_ratio']].to_string())

                                                                                                                                                                                                                                                                                title                    domain  score  num_comments  upvote_ratio
0                                                                                                                                                                                                                                    This was deleted twice from reddit's front page.               youtube.com  64503          2175          1.00
1                                                                                                                                 REMINDER: It has been 2866 days since Sean Hannity offered to undergo waterboarding for charity as proof that it's not torture and has not done it.        crooksandliars.com  42498          1472          1.00
2                                                                                                                                                                                                                                       Admins are editing our posts guys. It's over.                reddit.com  33132          2493          1.00
3                                                                                                                                                                                                                     Sources: Jeffrey Epstein dies by suicide in Manhattan jail cell                google.com  32373          5617          1.00
4                                                                                  Andrew Yang on Twitter: "Airlines got $25 billion in bailout money and cut 90,000 workers anyway. We are spending money to prop up companies that should just go directly to people and families."               twitter.com  31560          1307          0.93
5                            [Self/Meta] I have no dog in the fight, but let this be a lesson to the DNC and any other committee/agency that decides to play corrupt fuck-fuck games with American democracy. The other major Democrat candidate would've won the presidency. Period.           self.conspiracy  31220          1297          1.00
6                                                                                                                                           Every single time I post this video of Joe Biden groping the children of Senators for 12 minutes, it is removed or downvoted to oblivion.                  youtu.be  30419          2168          1.00
7                                                                                                                     I'm fucking TIRED of the fucking WAR on drugs. Jeff Sessions Demands "Strongest Possible Charges" For Drug Users. Fuck Jeff Sessions, and Fuck the War on Drugs               youtube.com  26420          2918          1.00
8                                                                                        Please make this go viral. I am begging you. Police and National Guard patrolling neighborhood and shooting civilians on their own property. Make America see this, I beg you. [Minneapolis]            streamable.com  26372          3345          0.89
9                                                                       Chinese Billionaire Says - The U.S. has wasted over $14 trillion on warfare over the past three decades — money that, could’ve been invested in domestic infrastructure and programs for the American people.                 sporte.ga  25777          1764          1.00
10                                                                                                                                                                            The Epstein court documents have just been released, over 2000 pages with list of people on that island         documentcloud.org  22865          2383          0.93
11                                                                                                                                              Ghislane Maxwell, long-time friend and confidante of Jeffrey Epstein, has been arrested by the FBI and charged by federal prosecutors            nbcnewyork.com  22663          2277          0.96
12                                                                                                                                                               Reddit actively removing video of Chinese police forcefully entering a woman's home to arrest her for internet posts               youtube.com  22287          2034          1.00
13                                                                                                                                Gunman kills son of federal judge Esther Salas at their home. The Jeffrey Epstein Deutsche Bank case was assigned to Judge Salas just two days ago.           nydailynews.com  22060          1658          0.97
14                                                                                                                   This was just censored from the #1 spot on /r/all; "Cops illegally confiscate guys phone and accidentally record themselves debating the best way to frame him".               youtube.com  21836           984          1.00
15                                                                                                                                         Due to Verizon's Super Bowl ad, remember that in the midst of raging wildfires Verizon throttled firefighters' data unless they paid more.                   npr.org  21829           444          1.00
16                                                                                               If you are a police officer and you are unwilling to run toward gunfire, to protect little kids..... Quit. Quit tomorrow. Find another job. Home Depot is hiring. Do something else.           self.conspiracy  21803          1855          0.92
17                                                                                                                                                                                                                                                           Sounds like a Conspiracy          files.catbox.moe  21310          1314          0.89
18                                                                      Chinese Billionaire Says - The U.S. has wasted over $14 trillion on warfare over the past three decades — money that, could’ve been invested in domestic infrastructure and programs for the American people.                accmag.com  21118          1674          1.00
19                                                                                            U.S. taxpayers gave $400 Billion dollars to cable companies to provide the United States with Fiber Internet. The companies took the money and didn't do shit for the citizens with it.               worights.cf  20427           892          1.00
20                                                                               Reddit Aggressively Censoring Content Critical of China: Story about Hearthstone player banned by Blizzard for pro-Hong Kong statement removed from THREE different subs on the front page of /r/all           self.conspiracy  19734           976          1.00
21                                                                                                                                                                                                                                                              Ah, the good old days          files.catbox.moe  19487           444          0.94
22                                                                                         TIL during the 2013 California drought, Nestle extracted 27,000,000 gallons of California drinking water for only $524, and resold it for millions. This received almost no news coverage.         healthnutnews.com  19419           734          1.00
23                                                                                            U.S. taxpayers gave $400 Billion dollars to cable companies to provide the United States with Fiber Internet. The companies took the money and didn't do shit for the citizens with it.        huffingtonpost.com  19385           760          1.00
24                                                                                                                                                                                   President Donald Trump thinks Scientology should lose its tax-exempt status in the United States               thehill.com  19383          1546          1.00
25                                                                                                                                                      Bernie Sanders’ Presidential Run Was Sabotaged by Fake News - 'Nobody worried about fake news when it helped Hillary Clinton'              observer.com  19336          1438          1.00
26                                                                                                                                         9/11 WTC Towers Had Power Turned Off For 36 Hours the Weekend Before the Attack - Security Systems disabled, unknown "workers" everywhere.          yournewswire.com  19285          3277          1.00
27                                                                                                         Dear r/the_donald. Stop using this sub to promote your candidate. This is a sub that holds TPTB accountable. Submit your criticisms of Trump. We don't need lap dogs here.           self.conspiracy  19103          2810          1.00
28                                                                                                  Mass media are keeping a lid on this. The DNC is trying to bury a class action law suit against them regarding them undemocratically favoring Hillary Clinton during the primary.          counterpropa.com  19077          1261          1.00
29                                                                                                                         Hillary Clinton's presidential campaign ends, and the next day an article detailing her financial ties to ISIS hits the front page of /r/politics. Finally                reddit.com  18451           738          1.00
30                                                                                          Saudi Arabia is mass murdering its Shia population and causing a genocide in Yemen. Meanwhile, the Reddit front page offers you a fawning photo of "Saudi man teaching his wife to drive"             np.reddit.com  18011           684          1.00
31                         Here is how Colorado is spending it's Cannabis Tax revenue: $40 million in school renovations, $6.7 million went to treatment programs, $8 million to combat HS drop outs and bullying. This is what they are waging war against. Never let ANYONE forget.           self.conspiracy  17756           857          1.00
32                                                                                                                                                                                                                                       Reports Allege Trump Has Deep Ties To Russia              buzzfeed.com  17328          4184          1.00
33                                                                                                                                                                                                                                                 Sometimes the Hippies Get it Right          files.catbox.moe  17213           872          0.90
34                                          Judge demands answers from Jeffrey Epstein’s estate after millions of dollars flood into his dormant offshore bank in the Virgin Islands, and then "disappear". This adds weight to the supposition that Epstein is alive, and in hiding.           dailymail.co.uk  17006           802          1.00
35                                                                                                                                                                                      FCC literally LAUGHING at the millions of comments of people pleading to save Net Neutrality.               youtube.com  16705          1567          1.00
36                                  It’s been nearly a week since former Joe Biden staffer Tara Reade leveled disturbing accusations of sexual misconduct against the Democratic presidential frontrunner, and yet ABC, CBS, NBC, MSNBC and CNN haven’t said a single word about them           newsbusters.org  16691          1336          1.00
37                                                                                                                                                                                                           At least historians will look back and say "Not EVERYBODY was crazy...."  external-preview.redd.it  16648          1242          0.84
38                                                    Dear Trump: the bill is now on your desk. Veto the shit out of it to protect the privacy of people YOU work for. Grow some balls and stand up to the swamp you supposedly were going to drain. If you don't, we WILL fight back           self.conspiracy  16565          2571          1.00
39                                                                                                                                                                                        Whitehouse.gov blocking petition to pardon whistleblowers. We need to blow this story open.           self.conspiracy  16305           331          1.00
40                                                                                                                               TIL The Susan G. Komen (Pink Ribbon/Breast Cancer) is a scam artist, her foundations takes in billions, but little goes back to those who need help.               youtube.com  16193           732          1.00
41  TIL Ron Paul has his own show on Youtube "The Ron Paul Liberty Report", It's still relatively new. He's been attacked from the left and right throughout his whole career, let's promote independent media channels willing to speak the truth. Check it out and spread the word!               youtube.com  16145           698          1.00
42                                                                       Senator Jon Tester: I was just handed a 479-page tax bill a few hours before the vote. One page literally has hand scribbled policy changes on it that can’t be read. This is Washington, D.C. at its worst.               twitter.com  16041          1768          1.00
43                                                                                                                                                      Welcome to 2021, where multi billion dollar oil companies lecture the average person on why they're damaging the environment.              i.postimg.cc  15942           492          0.92
44                                                                                                                                                                                                                                                                 Remember Gary Webb          files.catbox.moe  15795           454          0.97
45                                                                                    You want to talk about “looting”? Over the past 30 years the top 1% gained $21 trillion in wealth while the bottom 50% lost $900 billion in wealth. That is the only looting that I care about.               twitter.com  15374           673          0.85
46                                                                                                                                                                                         “Cannabis is not an entrance drug – it’s an exit drug from pharmaceuticals and narcotics.”                accmag.com  14908           815          1.00
47                                                                                                                                                                   I am combing through all the Epstein files. You asked for it. Here it is. PART 2 - The next 300+ page breakdown.           self.conspiracy  14864           898          1.00
48                                                                                                                                                                                                   Tonight Or Tomorrow A Billionaire NFL Owner Will Be Tied Human Trafficking In FL           self.conspiracy  14797           996          1.00
49                                 This is a warning to /r/ conspiracy: The burning of the library of Alexandria is repeating itself, with the same propagators; An elite bent on world dictatorship. And you know what is the "Library of Alexandria" of modern times? The Internet.           self.conspiracy  14724          1096          1.00